### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by ViniciusChrisosthemos** [smart-pucrs/MASiRe#7]
### TODO:
- [ ] Definir uma unidade para os passos da simulação;
- [ ] Refatoração da movimentação dos agentes;
  - [ ] Utilizar a escala do mapa para definir a distância percorrida;
  - [ ] Calcular a rota especial para os agentes terrestres/aquáticos.
- [ ] Adicionar caixa de  informações dos agentes no monitor;
- [ ] Criar mecanismo de leitura e reprodução de simulações;
- [ ] Retirar o vinculo dos ativos sociais com os eventos;
- [ ] Adicionar um serviço de calculo de rota independente do Simulador;
- [ ] Investigar o bug da ação pass;
- [ ] Retirar logs do monitor;
- [ ] Implementar o padrão RESTful para o monitor;
- [ ] Migrar a biblioteca PyRoute para Rana;
- [ ] Implementar a configuração mais precisa do eventos, permitindo o simulador criar ambiente de desastres genéricos;
### DOING:
- [x] ITEM FIXO.
### DONE:
- [x] ITEM FIXO.
